version: '3'
services:
  web:
    build: .
    command: bundle exec thin start --ssl -p 3001
    volumes:
      - .:/app
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
